# Generated by Django 3.1 on 2020-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_place',
            name='delivery_time',
            field=models.CharField(default='Will Be Update Soon', max_length=100),
        ),
        migrations.AddField(
            model_name='order_place',
            name='status',
            field=models.CharField(default='Order Confirmed', max_length=100),
        ),
    ]
