# Generated by Django 3.1 on 2020-10-09 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_place_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_place',
            name='order_place_date',
            field=models.DateField(default=datetime.date(2020, 10, 9)),
        ),
    ]
