# Generated by Django 3.1 on 2020-10-09 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_place_order_place_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_place',
            name='order_place_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 16, 19, 20, 971394, tzinfo=utc)),
        ),
    ]
