# Generated by Django 3.1 on 2020-10-09 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201009_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_place',
            name='order_place_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 9, 16, 19, 51, 8845, tzinfo=utc)),
        ),
    ]
