# Generated by Django 3.1 on 2020-10-22 06:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20201009_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_place',
            name='order_place_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 22, 6, 10, 31, 159306, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
