# Generated by Django 3.1 on 2020-10-24 14:01

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_auto_20201022_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
        migrations.AlterField(
            model_name='order_place',
            name='order_place_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 24, 14, 0, 59, 563681, tzinfo=utc)),
        ),
    ]
